runtime: python39  # Especifica la versión de Python que utilizas (por ejemplo, python39 para Python 3.9)
instance_class: F2  # Especifica la clase de instancia para tu aplicación (puedes ajustarla según tus necesidades)

handlers:
- url: /.*  # Maneja todas las solicitudes HTTP entrantes
  script: auto  # Ejecuta el script de tu aplicación automáticamente

env_variables:  # Define variables de entorno si es necesario
  KEY: 'value'
